name: Build-and-Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read          # PAT/keys, not OIDC
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with: { version: 9, run_install: false }
    - uses: actions/setup-node@v4
      with: { node-version: '20', cache: 'pnpm' }

    # ---------- Install workspace deps ----------
    - run: pnpm install

    # ---------- Build SvelteKit ----------
    - name: Build SvelteKit
      working-directory: app
      run: pnpm run build

    # -------- CDK Bootstrap --------
    - name: CDK Bootstrap
      working-directory: infra
      env:
        AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:            ${{ secrets.AWS_REGION }}
      run: |
        ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
        npx cdk bootstrap aws://$ACCOUNT/$AWS_REGION --require-approval never

    # -------- CDK Deploy --------
    - name: CDK Deploy
      working-directory: infra
      env:
        AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:            ${{ secrets.AWS_REGION }}
      run: |
        pnpm run build
        npx cdk deploy --require-approval never

